CREATE TABLE ALUMNO ( 
    TIPO_DOCUMENTO VARCHAR2(15), 
    DOCUMENTO NUMERIC(10), 
    NOMBRE VARCHAR2(40), 
    CIUDAD VARCHAR2(40), 
    CONSTRAINT ALUMNO_PK PRIMARY KEY (TIPO_DOCUMENTO, DOCUMENTO) 
);

CREATE TABLE PROFESOR ( 
    TIPO_DOCUMENTO VARCHAR2(15), 
    DOCUMENTO NUMERIC(10), 
    NOMBRE VARCHAR2(40), 
    TITULO VARCHAR2(40) CHECK (TITULO IN ('Phd', 'Msc', 'pregrado')), 
    CONSTRAINT PROFESOR_PK PRIMARY KEY (TIPO_DOCUMENTO, DOCUMENTO) 
);

CREATE TABLE SEMESTRE ( 
    ANO NUMERIC(4), 
    NUMERO NUMERIC(2), 
    FECHA_INICIO DATE, 
    FECHA_FIN DATE, 
    CONSTRAINT SEMESTRE_PK PRIMARY KEY (ANO, NUMERO) 
);

CREATE TABLE ASIGNATURA ( 
    ID NUMERIC(5) PRIMARY KEY, 
    NOMBRE VARCHAR2(40), 
    CREDITOS NUMERIC(1) 
);

CREATE TABLE GRUPO (  
    ID_ASIGNATURA NUMERIC(15),  
    NUMERO NUMERIC(2),  
    ANO_SEMESTRE NUMERIC(4),  
    NUMERO_SEMESTRE NUMERIC(2),  
    TIPO_DOCUMENTO_PROFESOR VARCHAR2(15),  
    DOCUMENTO_PROFESOR NUMERIC(10),  
    CONSTRAINT GRUPO_PK PRIMARY KEY (ID_ASIGNATURA, NUMERO, ANO_SEMESTRE, NUMERO_SEMESTRE),
    CONSTRAINT GRUPO_ASIGNATURA_FK FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA(ID),  
    CONSTRAINT GRUPO_SEMESTRE_FK FOREIGN KEY (ANO_SEMESTRE, NUMERO_SEMESTRE) REFERENCES SEMESTRE(ANO, NUMERO),  
    CONSTRAINT GRUPO_PROFESOR_FK FOREIGN KEY (TIPO_DOCUMENTO_PROFESOR, DOCUMENTO_PROFESOR) REFERENCES PROFESOR(TIPO_DOCUMENTO, DOCUMENTO)  
);

CREATE TABLE ALUMNO_GRUPO (  
    TIPO_DOCUMENTO_ALUMNO VARCHAR2(15),  
    DOCUMENTO_ALUMNO NUMERIC(10),  
    ID_ASIGNATURA NUMERIC(15),  
    NUMERO NUMERIC(2),  
    ANO_SEMESTRE NUMERIC(4),  
    NUMERO_SEMESTRE NUMERIC(2), 
    NOTA NUMERIC(4,2), 
    CONSTRAINT ALUMNO_GRUPO_PK PRIMARY KEY (TIPO_DOCUMENTO_ALUMNO, DOCUMENTO_ALUMNO, ID_ASIGNATURA, NUMERO, ANO_SEMESTRE, NUMERO_SEMESTRE),
    CONSTRAINT ALUMNO_GRUPO_ASIGNATURA_FK FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA(ID),  
    CONSTRAINT ALUMNO_GRUPO_SEMESTRE_FK FOREIGN KEY (ANO_SEMESTRE, NUMERO_SEMESTRE) REFERENCES SEMESTRE(ANO, NUMERO),  
    CONSTRAINT ALUMNO_GRUPO_ALUMNO_FK FOREIGN KEY (TIPO_DOCUMENTO_ALUMNO, DOCUMENTO_ALUMNO) REFERENCES ALUMNO(TIPO_DOCUMENTO, DOCUMENTO)  
);
